/*
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
 */

object Two {

  def main(args: Array[String]): Unit = {
    val ceiling = 4000000
    var terms = Array(1, 2)
    var sum = 0

    do {
      if (terms(1) % 2 == 0) {
        sum += terms(1)
      }
      terms = Array(terms(1), terms.sum)
    } while (terms(1) <= ceiling)

    println(s"$sum")
  }

}
